cryptapps/cryptapps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('cryptids/', include('cryptids.urls')),
    path('admin/', admin.site.urls),
]

cryptapps/cryptids/urls.py
from django.urls import path

from . import views

from django.urls import path

from . import views

app_name = 'cryptids'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:cryptid_id>/', views.detail, name='detail'),
]

# Here is all the urls used by the app

cryptapps/cryptids/models.py
from django.db import models


class Habitat(models.Model):
    country_name = models.CharField(max_length=200)
    continent = models.CharField(max_length=200)

    def __str__(self):
        return self.country_name


class Cryptid(models.Model):
    # The main class for the app
    cryptid_name = models.CharField(max_length=200)
    aggressive = models.BooleanField(True)
    habitat = models.ForeignKey(Habitat, on_delete=models.CASCADE)

    def __str__(self):
        return self.cryptid_name

    # Makes it so calling the instance of the class shows its name instead of the index number.

    def behaviour(self):
        if self.aggressive:
            return "Aggressive"
        else:
            return "Peaceful"

    # Rather than calling the aggressive variable, the app will call this function to make it
    # easier for the user to read the creature's behaviour.

    def get_habitat(self):
        return self.habitat.country_name

    # Gets the cryptid's habitat's name, as calling the habitat may results in showing its index number.


class Sighting(models.Model):
    sighting_site = models.CharField(max_length=200)
    sighting_date = models.DateTimeField('Happened in')
    cryptid = models.ForeignKey(Cryptid, on_delete=models.CASCADE)

    def __str__(self):
        return self.sighting_site

# Create your models here.

cryptapps/cryptids/views.py
from django.shortcuts import get_object_or_404, render
from .models import Cryptid
from django.template import loader


# Here is the two views linked to the pages we can find in the app: index, for the index, and detail, seen when
# clicking on the cryptid we want to learn more about


def index(request):
    cryptids_list = Cryptid.objects.order_by('cryptid_name')
    template = loader.get_template('cryptids/index.html')
    context = {
        'cryptids_list': cryptids_list
    }
    return render(request, 'cryptids/index.html', context)


def detail(request, cryptid_id):

    cryptid = get_object_or_404(Cryptid, pk=cryptid_id)
    return render(request, 'cryptids/detail.html', {'cryptid': cryptid})


cryptapps/cryptids/templates/cryptids/detail.html
<h1>{{ cryptid.cryptid_name }}</h1> <!-- Display the cryptid's name -->
<h2>Behaviour: {{ cryptid.behaviour }}</h2> <!-- Displays the behaviour's function result -->
<h2>Habitat: {{ cryptid.get_habitat }}</h2> <!-- Displays the cryptid's habitat's name -->
<h2>Related incidents:</h2>
<ul>
<!-- Displays a list of all incidents linked to the cryptid, by looking at all the Sighting linked to the Cryptid-->
{% for sighting in cryptid.sighting_set.all %}
    <li>{{ sighting.sighting_date }}, in {{sighting.sighting_site}}</li>
{% endfor %}
</ul>
<h3><a href="{% url 'cryptids:index' %}">Back to index</a></h3> <!-- A hyperlink to go back to the index -->

cryptapps/cryptids/templates/cryptids/index.html
<h1>Cryptids record</h1>

<h2>Here is a list of all the recorded cryptids in the app:</h2>
{% if cryptids_list %} <!-- If else in case there is no cryptids -->
    <ul>
    {% for cryptid in cryptids_list %} <!--Displays a list of all the cryptids registered in the app -->
        <li><a href="{% url 'cryptids:detail' cryptid.id %}">{{ cryptid.cryptid_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No cryptid registered yet.</p>
{% endif %}